from flask import Flask, request, jsonify
import os
import tempfile
import subprocess

app = Flask(__name__)

@app.route("/", methods=["GET"])
def hello():
    return jsonify({"message": "hello world", "status": "ok"})

@app.route("/health", methods=["GET"])
def health():
    """Health check endpoint"""
    return jsonify({"status": "healthy", "service": "ocr-api"}), 200

@app.route("/diagnostics", methods=["GET"])
def diagnostics():
    """Diagnostic endpoint to check chandra CLI availability"""
    diagnostics_info = {
        "cli_available": False,
    }
    
    # Check if CLI is available
    try:
        result = subprocess.run(['chandra', '--help'], 
                              capture_output=True, 
                              text=True, 
                              timeout=5)
        diagnostics_info["cli_available"] = result.returncode == 0
        if diagnostics_info["cli_available"]:
            diagnostics_info["cli_help"] = result.stdout[:500]  # First 500 chars
    except (FileNotFoundError, subprocess.TimeoutExpired, Exception):
        diagnostics_info["cli_available"] = False
    
    return jsonify(diagnostics_info)

@app.route("/ocr", methods=["POST"])
def ocr_image():
    if "image" not in request.files:
        return jsonify({"error": "No image file provided"}), 400

    file = request.files["image"]
    # Use tempfile to handle temp files properly
    with tempfile.TemporaryDirectory() as temp_dir:
        image_path = os.path.join(temp_dir, file.filename)
        file.save(image_path)

        try:
            # Create output directory within temp_dir
            output_dir = os.path.join(temp_dir, "output")
            os.makedirs(output_dir, exist_ok=True)

            # Run chandra CLI with hf method (local HuggingFace inference)
            subprocess.run(
                ['chandra', image_path, output_dir, '--method', 'hf'],
                check=True,
                capture_output=True,
                text=True
            )

            # Find the output markdown file
            base_name = os.path.splitext(file.filename)[0]
            md_path = os.path.join(output_dir, f"{base_name}.md")

            if os.path.exists(md_path):
                with open(md_path, 'r', encoding='utf-8') as f:
                    result_text = f.read()
            else:
                # Fallback: look for any .md file
                output_files = [f for f in os.listdir(output_dir) if f.endswith('.md')]
                if output_files:
                    md_path = os.path.join(output_dir, output_files[0])
                    with open(md_path, 'r', encoding='utf-8') as f:
                        result_text = f.read()
                else:
                    raise Exception("No output markdown file generated by chandra.")

            output = {"text": result_text}
        except subprocess.CalledProcessError as e:
            error_msg = f"chandra CLI failed: {e.stderr}"
            return jsonify({"error": error_msg}), 500
        except Exception as e:
            return jsonify({"error": str(e)}), 500

    return jsonify(output)

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)